[package]
name = "mwaka-aria"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
publish = true
description = "A collection of libraries and tools that help you build DDD, CQRS, and event sourcing."
repository = "https://github.com/timayz/mwaka"
documentation = "https://docs.rs/mwaka-aira"

[dependencies]
